# Everforest dark – kitty color scheme (rice2)

foreground            #d3c6aa
background            #1e2326
selection_foreground  #d3c6aa
selection_background  #374145

cursor                #d3c6aa
cursor_text_color     #1e2326

url_color             #83c092

active_border_color   #83c092
inactive_border_color #374145
bell_border_color     #dbbc7f

# Tab bar
active_tab_foreground   #1e2326
active_tab_background   #83c092
inactive_tab_foreground #9da9a0
inactive_tab_background #272e33
tab_bar_background      #1e2326

# Black
color0  #4b565c
color8  #575e64

# Red
color1  #e67e80
color9  #e67e80

# Green
color2  #a7c080
color10 #a7c080

# Yellow
color3  #dbbc7f
color11 #dbbc7f

# Blue
color4  #7fbbb3
color12 #7fbbb3

# Magenta
color5  #d699b6
color13 #d699b6

# Cyan
color6  #83c092
color14 #83c092

# White
color7  #d3c6aa
color15 #d3c6aa
