# kitty — rice2 (Iosevka Nerd Font · Everforest dark)

font_family      Iosevka Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

cursor_shape               block
cursor_blink_interval      0.5
cursor_stop_blinking_after 1

scrollback_lines           5000
wheel_scroll_min_lines     1
touch_scroll_multiplier    4

enable_audio_bell          no

window_padding_width       10
hide_window_decorations    yes
background_opacity         0.90
dynamic_background_opacity yes
confirm_os_window_close    0

selection_foreground       none
selection_background       none

tab_bar_style              powerline
tab_powerline_style        slanted
tab_bar_min_tabs           2

linux_display_server       wayland
sync_to_monitor            no
wayland_enable_ime         no

include colors.conf
